# Generated by Django 6.0.6 on 2026-08-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'verbose_name': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='documentmodel',
            options={'verbose_name': 'Document'},
        ),
        migrations.AlterModelOptions(
            name='documenttypemodel',
            options={'verbose_name': 'Document Type'},
        ),
    ]
